[package]
name = "clippy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.27.0"
lodepng = "3.9.1"
repng = "0.2.2"
scrap = "0.5.0"
